app/config.py
scripts/setup_data.sh
tests/integration/test_integration.py

Integration test would fail as [the new case endpoint](https://github.com/ONSdigital/rm-case-service/pull/55) (`/cases?sampleUnitId=[uuid]`) returns a list of cases.
Other fixes for using master of setup tools and config (localhost: aligns with other services defaults) and string comparison and waiting for iac.
`make test` for...  🍰 !

Fix integration tests

---

app/templates/base.html

"Contact us" and "Cookies and privacy" links now pointing to equivalent pages on the ONS website.
Fixes: #27

Fixed the broken links in the footer

---

.flake8
app/app.py
app/app_logging.py

- Removed reference to secure message in initial logging setup 
- Increased flake8 line limit to 160
- Added missing line padding in app.py

Remove reference to secure message in log setup

---

app/eq.py

The collection exercise event dates are non-mandatory for LMS to run the survey in eQ. They are, however, passed to SDX if present.
Remove the enforcement of mandatory for a CE event dates in Respondent Home UI.
Run the unit tests (`make unittests`) and/or launch a new UAC from a collection exercise without event dates (return by, start date, end date) set.

Event dates are optional in LMS

---

app/eq.py
tests/demo/demo.py
tests/unit/__init__.py
tests/unit/test_eq.py

A sample file has no concept of a region code and previously we were hard coding it to "GB-ENG". Following a [recent change to the schema in eQ Runner](https://github.com/ONSdigital/eq-survey-runner/pull/1705) we can drop it in favour of expecting a country code from the sample attributes instead.
- Expect a country code present in the sample attributes
- Remove region code from the payload
- Update to the unit tests to fail on missing country code
`make test` should do it
- [eQ runner PR introducing the country code](https://github.com/ONSdigital/eq-survey-runner/pull/1705)
- [LMS 1 schema](https://github.com/ONSdigital/eq-survey-runner/blob/master/data/en/lms_1.json)

Require country code in eQ payload

---

Pipfile.lock
app/app.py
app/config.py
app/handlers.py
tests/test_data/local.env

NB: This will require the environment variables for EQ_URL to be updated to only include host, protocol and port. 
It was [pointed out](https://github.com/ONSdigital/ras-deploy/pull/55#discussion_r206826554) that the full path does not change between environments. This pins the full path to eQ to the redirect URL line only.
Expect `[protocol]://[host](:[port])` only in the environment variable `EQ_URL`. Full path built at redirect time.
Took the opportunity to update insecure packages.
`make unittests` or `make test` for the full end-to-end (with eQ runner).
https://github.com/ONSdigital/ras-deploy/pull/55

Have full eQ path only in redirect line

---

app/eq.py
tests/unit/__init__.py
tests/unit/test_eq.py

Change the display address to contain 'district', 'post_town',
'postcode' if present and 2 fields haven't already been populated. Also
comma separating
Add 'district', 'post_town', 'postcode' to display address
Comma separating address
Run unit tests
https://trello.com/c/DKeaOOEE/178-send-address-and-country-code-to-eq-from-rh-5

Change format of display address

---

tasks.py
tests/smoke/test_respondent_home.py

The pipeline [defines a single environment variable](https://github.com/ONSdigital/ras-deploy/blob/f2d650b9c8a5a665eb72f23c63ba1b5b026d1104/pipelines/respondent-home-ui.yml#L121) for the RH smoke test called RESPONDENT_HOME_URL, the incorrect assumption in #38 was made that the rest of the application's environment was available to the smoke test. 
Revert back to using RESPONDENT_HOME_URL and add a `--local` flag to `inv smoke`.

Revert config changes to smoke and add local flag

---

app/eq.py
app/handlers.py
tests/integration/test_integration.py
tests/unit/__init__.py
tests/unit/test_eq.py

**Do not merge until confirmation of eQ changes for this PR**
It's a SHA256 hash of case_id|collex_id|iac
Addressed Jamie's (verbal) PR comments
- added logging & doc string to build_response_id
In order for issuing new IACs to be an information safe operation, activating EQ with a new IAC must launch a new version of the survey questionnaire and not show any previously entered responses.  Currently EQ use the case to identify the responses to be displayed.  Where there are multiple response sets for a case (e.g. where a new IAC has been issued), this is insufficient.  This PR adds an additional field to the JWT claims that go to EQ: response_id.  
- added a build_response_id function to eq.py
- added response_id field to JWT payload 
- navigate to RH
- enter valid IAC into RH
- confirm …

Added a respondent_id to the JWT claims

---

app/templates/base.html

The "Cookies and privacy" link should point to https://surveys.ons.gov.uk/cookies-privacy as the information in more relevant/GDPR compliant
The "Cookies and privacy" link
link should now go to https://surveys.ons.gov.uk/cookies-privacy

update the "cookies and privacy" link to point to the correct location

---

ci/smoke_tests.sh

After a recent merge to master on this repo, the smoke test script was failing in the pipeline when running `pipenv install --dev` during an install of the pyyaml package. The error was as follows:
```
ext/_yaml.c:4:10: fatal error: Python.h: No such file or directory
#include "Python.h"
^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```       
* Added an install for python3-dev before pipenv runs.
* I have connected to the failing container in the pipeline and run the script manually and the smoke tests are able to run successfully. You can follow the same steps [here](https://github.com/ONSdigital/ras-deploy#job-failed-in-pipeline) to do the same.

Add python3-dev install for smoke test

---

tests/smoke/test_respondent_home.py

The pipeline failed to deploy due to a failing smoke test caused by a change in the [HTML text](https://github.com/ONSdigital/respondent-home-ui/blob/3447cc16ac954165c667cca851d57d682ff631e6/app/templates/base.html#L43). 
We agreed that this can be removed in favour of future text changes, to prevent it failing again. The HTTP 200 check when the response is returned should be fine for a smoke test for now.
`test_respondent_home.py`
Run the smoke test in the pipeline after merging.

Remove text assert for smoke test

---

app/exceptions.py
app/handlers.py
tests/unit/test_handlers.py

Respondent Home needs to return a 202 http status code when an IAC code is entered but not found, this is to enable a WAF rule which will block IP's on multiple failed IAC attempts.
If the IAC is invalid the response raised is now HTTPAccepted. Unit test looking for 404 messages from the IAC service is now checking the response is 202.
Run the unit tests.
https://trello.com/c/Rymy0bKn

If IAC is invalid the response is changed to HTTPAccepted (202)

---

app/__init__.py
app/handlers.py
app/templates/base.html
app/templates/index.html
app/templates/partials/messages.html
tests/unit/__init__.py
tests/unit/test_handlers.py

Currently every message flashed is treated as an error. This PR adds the functionality to handle levels of messages and render the related panel type from the pattern library. 
- Adds functionality to respondent home for rendering non-error level messages in templates using the pattern library panels.
- Adds additional field "level" (currently only ERROR or INFO) to the message dicts.
- Adds an HTML partial for handling the message logic and rendering appropriately.
- Adds missing title tag to the base template.
- Use correct error message for an invalid code.
Unit tests:
`make unittests`
Functionality:
1. Start locally and attempt to navigate to respondent home: http://localhost:9092
2. Check the rendered messages against "Message Slides" (attached to Trello card).
NB: WIP as missing …

Render messages based on level

---

ci/smoke_tests.sh

The smoke tests in the concourse-latest space failed due to the current issue with [pipenv and the use of pip v18.1](https://github.com/pypa/pipenv/issues/2924). 
For the workaround, pin the pip version to the previous working version 18.0 for the smoke test script.
Locked the pip version to 18.0 for the smoke tests.
Ensure the integration tests still pass locally.
The changes have already been flown to the pipeline. This is just to keep the pipeline source up to date.
N / A

Add pip workaround for pipenv

---

app/app.py
app/config.py
app/eq.py
app/error_handlers.py
app/handlers.py
app/routes.py
app/templates/base.html
app/templates/index.html
tests/unit/__init__.py
tests/unit/test_app.py
tests/unit/test_error_handlers.py
tests/unit/test_handlers.py

The application needs to handle an optional URL path component prefix which can be configured when deployed. The `/info` route is needed for health-checks, so do not prefix anything for this route. We were unable to configure the manifest to accept variable substitution with Concourse when the app is deployed, so we explicitly ignore this via the code.
The [pipeline changes](https://github.com/ONSdigital/ras-deploy/compare/add-url-path-prefix-for-rh?expand=1) are in place ready for this PR.
* Changed app creation behaviour to allow URL prefix when app routes are mapped.
* Ignore URL prefixing for `/info` for health-checks. 
1. Edit your `.env` file and set `URL_PATH_PREFIX=/test-prefix`
2. Open Respondent Home UI with the prefix, e.g. `localhost:9092/test-prefix`
3. Ensure the page …

Make URL path prefix configurable

---

app/eq.py
tests/demo/demo.py
tests/integration/test_integration.py
tests/test_data/collection_instrument/collection_instrument_eq.json
tests/unit/__init__.py
tests/unit/test_eq.py

The `ru_name` is not a relevant field for social surveys and has been removed from the EQ LMS schema.
* removed ru_name from eq payload
* removed test for ru_name
* removed ru_name from test data
All functionality should remain the same, just the payload no longer contains `ru_name`
To run the integration tests locally you'll need changes on this branch of rm-tools: https://github.com/ONSdigital/rm-tools/pull/28
Modify the data_setup.sh script to point to that branch like this:
```shell
git clone --depth 1 ${rm_tools_repo_url} --single-branch -b update-social-eq-form-type tmp_rm_tools;
```
Then the integration tests should pass
https://trello.com/c/QwnRHhx2/291-defect-respondent-home-ui-tries-to-use-addressline1-as-runame
https://github.com/ONSdigital/rm-tools/pull/28

Remove ru_name from eq payload

---

tasks.py
tests/smoke/test_respondent_home.py

Now that this app can be configured to handle a URL path prefix, we need to ensure that when smoke tests are run, the app is configured as we expected.
Updated smoke test to ensure `URL_PATH_PREFIX` is used. This will default to an empty string if not set. This variable is set by the pipeline before a smoke test is run. 
Dependent on [this PR](https://github.com/ONSdigital/ras-deploy/pull/86)
* Set `URL_PATH_PREFIX=/testpathprefix`
* `make run`
* In a separate command line `pipenv run inv smoke --local` 
Repeat above, and ensure `URL_PATH_PREFIX` is unset.
[Trello](https://trello.com/c/vteevzP4/219-sus012-ext-setup-url)

Update smoke test assertion

---

app/handlers.py
app/templates/cookies-privacy.html
app/templates/partials/footer.html
app/templates/partials/header.html

Create privacy page for social.
- New privacy page created.
- Pointed footer link to new page.
- Added logo link back to RH.
Check links work and content is correct (see: https://docs.google.com/viewerng/viewer?url=https://trello-attachments.s3.amazonaws.com/5a159c97a25f12ca639acf71/5b9a4c99a879363966d9d7a3/de6c76a030675e74ca318c23fb00bb45/Cookies_and_Privacy_(Social)_SBL_1.docx)
https://trello.com/c/d0U2sz8L/278-sus021-update-to-content-of-surveys-privacy-page-to-include-information-for-social-surveys

Sus021 privacy page update

---

app/app.py
tests/unit/test_app.py

When running Respondent Home locally, an accompanying [aux server](https://github.com/aio-libs/aiohttp-devtools/) is usually started alongside on PORT+1. This additional server adds the functionality for live reloading, as well as other helpful dev tools. With security headers applied to the dev server these tools no longer function.
- Disable security headers when running in debug mode.
- Force security headers to be applied when testing app creation.

T007 Only apply security headers when not in debug mode

---

Makefile

Following the [addition](https://github.com/ONSdigital/ras-deploy/pull/79) of a [re-usable unit test task](https://github.com/ONSdigital/ras-deploy/blob/95bc9ef4783759658f961010c7e713dfc414fd90/tasks/python-unit-tests.yml) in the deployment pipeline, we should make sure a project's Makefile targets are generic (e.g.: `make build`, `make test`, etc.).
- added `make build` as an alias for `pipenv install --dev`
- changed `make test` to only run the unit tests
- added `make local_test`, which runs the integration tests only

Change make targets to something more generic for use in pipeline

---

app/error_handlers.py
tests/unit/test_error_handlers.py

Following the [removal of the static files](https://github.com/ONSdigital/respondent-home-ui/pull/59), a bug was introduced whereby an incomplete prefixed path would not resolve to index.
This manifested because previously a prefixed path such as `/mystudy` would go to the static root directory -> which we made inaccessible -> app raises 403 (forbidden) -> error handler redirects to index.
- Add a custom error handler for paths not found to check for an incomplete index route and redirect if possible (301)
- Reinstate unit test for redirecting to index
- run the unit tests with `make unittests`
- start the server with `make run` and check routing with and without a URL_PATH_PREFIX environment variable

BUG303 Redirect prefixed paths missing a trailing slash to index

---

app/handlers.py
app/templates/contact-us.html
app/templates/error.html
app/templates/partials/footer.html
tests/unit/__init__.py
tests/unit/test_handlers.py

Respondent home footer link needs a contact page containing social business contact details.  This is a duplicate of the eQ social contact page with rh header and footer.
- Created contact page on rh
- Linked footer and 500 error page to new contact page
- Unit tests.
- Check content of contact us is correct
- Check links in footer and error page
https://trello.com/c/59NWvs2p/316-sus053-create-contact-us-content-and-page

SUS053: Create contact us content and page.

---

app/__init__.py
app/eq.py
app/error_handlers.py
app/exceptions.py
app/templates/closed.html
scripts/setup_data.sh
tests/test_data/collection_exercise/collection_exercise_events_closed.json
tests/test_data/collection_exercise/test-1-events.csv
tests/unit/__init__.py
tests/unit/test_eq.py
tests/unit/test_handlers.py

As a: Social Survey Team Member
I need: A given Collection Exercise to close and become unavailable when the "End Date" is reached
So that: Respondents can no longer access the EQ
[SUS013](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/756908125/SUS013+Close+Collection+Exercise)
- Added an error handler which renders a page when accessing a collection exercise with an end date that is already in the past
- Separated the parsing and formatting logic of datestrings.
- Refactored payload builder class to include event-related methods.
- Added a new data file for loading collection exercise events with rm-tools.
- Added and updated unit tests.
- Run the unit tests and flake8 (`make test` for both)
- Amend a collection exercise event with the tag "ref_period_end" to something in the …

SUS013 Make an eQ inaccessible if past the CE end date

---

app/__init__.py
app/case.py
app/error_handlers.py
app/handlers.py
app/templates/completed.html
tests/unit/test_handlers.py

Send user to page when they enter an access code that has already been used to submit a completed study.  
Note: This page should take precedence over the study closed message if the user has completed the survey. 
- Check page displays if user submits an IAC in RH that has already been used to complete a study.
- Check above scenario after a collection exercise has closed.
https://trello.com/c/BJrPLZoZ/306-sus054-it003-user-enters-a-code-for-a-completed-study

SUS054 / IT003: User enters a code for a completed study

---

app/eq.py
tests/test_data/collection_exercise/collection_exercise_events.json
tests/test_data/collection_exercise/collection_exercise_events_closed.json
tests/test_data/collection_exercise/test-1-events.csv
tests/unit/__init__.py

Previously, RH was (incorrectly) using the "period end" to check whether a collection exercise had ended. This fix adds the use of the "exercise_end" tag, which will also (harmlessly) be passed to the payload as the same key.
- Added the fetching and parsing of event with the tag "exercise_end" during payload creation
- Updated unit tests and test data
- Made sure "exercise_end" was present and after "mps" in the integration test data

Fix / SUS013: Use the exercise_end event to check whether a CE has closed

---

scripts/flush.py

As a: Social Surveys Team member
I need: The partial response data to be flushed downstream
So that: Partial data (Surveys that are in an "In Progress" state) can also be included with complete responses when a Collection Exercise is closed
A python script has been written and placed in the scripts directory, when called with a collection ID from the command line this gets information about the cases to generate a token to submit to the EQ flush endpoint.
Have the rasrm docker dev containers running, along with the EQ survey runner containers. Create a collection exercise using the rasrm ops tool. Start an EQ survey using one of the cases from the collection exercise (but don't finish it!). Tail the EQ survey runner logs and run the script using:
pipenv run python scripts/flush.py …

Script to flush partial responses from eq

---

scripts/flush.py

The flush script did not indicate the response from the EQ flush endpoint, this PR adds it in.
Added printing of the response from the EQ flush endpoint
Like before, have EQ survey runner docker containers running alongside the docker dev containers and start a collection exercise. Partially complete some and then run the flush script:
pipenv run python scripts/flush.py _collection-exercise-id
You should see the response from the EQ flush printed out in the terminal you ran the script from.  
https://trello.com/c/lNmyBmPH/214-sus014-send-partial-data-downstream-13

Add response logging to flush script

---

app/config.py

If cloud foundry is detected (using REDIS_SERVICE), REDIS_HOST and REDIS_PORT will be populated after app setup. To avoid ConfigurationError being raised these should be optional (default: empty string) in production.

Make redis host and port config variables optional

---

pytest.ini

Quick fix to stop the spammy messages produced from deprecation warnings regarding router argument in app setup.
Pytest config added to ignore DeprecationWarning but elevate any others to Error.
`make test`
[#2252](https://github.com/aio-libs/aiohttp/issues/2252)
[#85](https://github.com/ONSdigital/respondent-home-ui/issues/85)

TBL Ignore deprecation warnings from unittests and elevate others to error

---

pytest.ini

Pytest was set to error on warnings in the unit tests, but the smoke tests are also run with the same pytest config causing errors in the smoke tests in the pipeline.
- Do not raise error on warnings in pytest
#92

revert error on pytest warnings

---

Pipfile
Pipfile.lock

See https://github.com/aio-libs/aiohttp/issues/2766
Version 4.x of [aiohttp](https://github.com/aio-libs/aiohttp/) will [remove router as an argument](https://github.com/aio-libs/aiohttp/pull/3021) from app creation. 
This change pins RH to version 3 of aiohttp while the work to refactor the view routing away from depending on (the unmaintained) [aiohttp-utils](https://github.com/sloria/aiohttp_utils) is still yet to do.
Updated pinned version of aiohttp in Pipfile and relocked packages
`make build test`
- Issue https://github.com/ONSdigital/respondent-home-ui/issues/85 tracking the deprecation in RH with further reading

TBL Pin aiohttp to version 3 to workaround issue with router usage

---

app/error_handlers.py
app/exceptions.py
app/handlers.py
app/templates/inactive-iac.html
tests/unit/test_handlers.py

Display different pages for completed cases and inactive iac codes for other reasons
Currently this app displays a 'case completed' page when any inactive iac is used.  This is correct if the case is completed.  However it's possible in social for a refusal 562 for an iac to be set to inactive.  In this case the page should be say that the iac is inactive
- New html page inactive-iac.html added.  
- New code to check if an inactive iac is for a completed case or not.
- Renamed some variables and functions.  Extracted sample unit type check to seperate
- test_post_index_iac_active_missing, test_post_index_case_complete,
test_missing_case_group_status, test_post_index_iac_inactive
Checkout this branch.  
In ras-rm-docker-dev do **make pull**
In respondent-home-ui run docker **build . -t …

Display different pages for completed cases and inactive iac

---

app/eq.py
tests/unit/test_eq.py

"When Collection exercise event dates are added through Response-Ops, they are converted to UTC prior to being stored and are converted back to local time to be displayed on the collection exercise page, which is all good.
[This service] retrieves the collection exercise dates to form part of the eq_payload but doesn't convert the dates from UTC. We only send the date part of the date/time string and this has resulted in us passing incorrect dates to eQ." - spotted in ras-frontstage.
- Doing .[asTimeZone](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone)() brings the iso8601 parsed date back from UTC to the server local timezone
- Added contrived unit test
`make test`
- [Related frontstage PR](https://github.com/ONSdigital/ras-frontstage/pull/422)

Convert incoming UTC dates to system local

---

_infra/helm/respondent-home-ui/Chart.yaml
_infra/helm/respondent-home-ui/templates/deployment.yaml
_infra/helm/respondent-home-ui/values.yaml

Adds kube_dns addresses for all connecting services to allow us to have circular references

Create DNS entries for each service

---

_infra/helm/respondent-home-ui/templates/deployment.yaml
_infra/helm/respondent-home-ui/values.yaml

The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)

added devRepo
