ONSdigital/respondent-home-ui

locale/cy.yml

Added home_heading1 and encoded about_census right single quote.

---

locale/cy.yml

First, rough translation, of the error strings for demo.

Additional error strings. (1st pass translation)

---

locale/cy.yml

Added the official/approved translation strings supplied by Ll. Merriman.

Added corrected and approved translations of English strings

---

manifest.yml

To deploy to cloudfoundry the app needs a manifest file
Verify concourse pipeline respondent-home-ui is green for latest
https://trello.com/c/SwkUMf9O/99-dev-task-7-ext-access-eq-social-survey-rh

Add default manifest

---

.github/PULL_REQUEST_TEMPLATE.md

Just making this repo consistent with our other services by adding a PR template

added pr template file

---

README.md

The [ONS Schema Definitions](http://ons-schema-definitions.readthedocs.io/) is hosted on RTD. The details added to the README will be needed for reference for future development work that affect the eQ payload.
Added link to the page with required fields to launch an eQ.

Update README to link to the required fields for an eQ

---

app/eq.py
app/error_handlers.py
app/handlers.py
app/jwt.py
tests/integration/test_integration.py
tests/unit/test_app.py
tests/wait_for_services.py

Fix import ordering

---

app/static/css/responsive.css
app/templates/base.html
app/templates/index.html
app/templates/partials/footer.html
app/templates/partials/header.html
app/templates/partials/messages.html
tests/unit/test_error_handlers.py
tests/unit/test_handlers.py

Update headers and footers on RH to use those in [sdc-pattern library](https://sdc-global-design-patterns.netlify.com/components/detail/header.html) to ensure user experience is consistent when passing to eQ.
- Replaced page header with pattern library component
- Replaced page footer with pattern library component 
Additional pattern library markup alignment:
- Updated head to use styles and images from latest version of patter library on cdn
- Replaced js scripts in RH to use those from pattern library on CDN
- Updated markup for confidentiality message to use pattern library markup
- Added PL 'skip to content' accessibility link
Bug fixes:
- Fixed broken error message anchor link
Content changes:
- Updated page content to improve UX/readability
- Pointed 'what we do' footer link to …

Sus020 rh headers and footers

---

app/__init__.py
app/handlers.py
app/templates/partials/messages.html
tests/unit/__init__.py
tests/unit/test_handlers.py

Iteration on invalid and empty code messages.
- Invalid code message is now improved and displayed
- Empty code message (when HTML5 is not available) has been improved
- "must be corrected" has been removed from the error panel
Scenario 1: User hits Start without entering an access code. User needs to be informed that there is an error. Content iteration attached 
(There is HTML5 validation on the form to stop this but we need to account for the browsers that don't support this so still need server side validation)
Scenario 2: User enters an invalid access code. User needs to be informed that there is an error. Content iteration attached

IT002 Display invalid code message and remove must be corrected

---

README.md

Update readme to align with makefile changes

---

tests/demo/demo.py
tests/test_data/sample/sample_attributes.json

Changes required to keep up with schema changes that have since been applied to eQ.
Added required field for address line 2.
Removed unused variables in demo.
`make demo`

Update demo runner to work with recent eq changes

---

app/error_handlers.py
app/templates/404.html
tests/unit/test_error_handlers.py

Currently when a user attempts to access a page/route that doesn't exist a standard 404 text message is returned.
- new 404 html template
- added handler for any NotFoundError raised and 404 responses
- added simple unit test
Start RH and enter add any /unknown path to the localhost app URL in a browser.

SUS404 Add 404 not found page and handler

---

Pipfile.lock

GitHub flagged an insecure version of the Requests package.
- All packages have been updated to their latest versions (where possible).
`make test`
- Screenshot attached

T008 Update packages to latest version

---

Dockerfile

Use smaller base image for Docker container.

---

manifests/manifest-prod.yml

NB: Includes the res-ops-redis service definition.

Add manifest for pre-prod and prod environments

---

app/__init__.py
scripts/planned_maintenance.py
tests/unit/test_middleware.py

Improve help of planned maintenance script to show message usage

---

Pipfile
Pipfile.lock
scripts/deactivate_iac.py

We need to disable all the IACs for a Collection Exercise when it is closed.
New script has been added to deactivate IACs.
Run RASRM in Docker locally
Create Social Collection Exercise
When survey is live, get Collection Exercise ID from database
Manually run script to disable IAC

New script to disable IACs for a Collex.

---

_infra/helm/templates/deployment.yaml

Remove label version. its out of place and doesnt fit with the other servics

remove version

---

_infra/helm/templates/deployment.yaml

Add always pull policy until preprod is thoroughly tested

Add always pull policy

---

_infra/helm/respondent-home-ui/templates/deployment.yaml
_infra/helm/respondent-home-ui/values.yaml

remove database config

---

_infra/helm/respondent-home-ui/templates/deployment.yaml
_infra/helm/respondent-home-ui/templates/service.yaml
_infra/helm/respondent-home-ui/values.yaml

add managed redis template

---

_infra/helm/respondent-home-ui/values.yaml

The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)

changed service port

---

_infra/helm/respondent-home-ui/Chart.yaml
_infra/helm/respondent-home-ui/templates/deployment.yaml
_infra/helm/respondent-home-ui/values.yaml

Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)

added if-statement for variable versions
